In [40]:
import matplotlib.pyplot as plt

In [28]:
import os

In [42]:
from geojson import Point

ModuleNotFoundError: No module named 'geojson'

In [35]:
!pip3 install geojson

Requirement already satisfied: geojson in /home/anagarcia/anaconda3/envs/final/lib/python3.8/site-packages (2.5.0)

In [43]:
!pip3 list

Package           Version
----------------- -------------------
astroid           2.4.2
cachelib          0.1.1
certifi           2020.12.5
click             7.1.2
EcoNameTranslator 2.1
Flask             1.1.2
Flask-PyMongo     2.3.0
Flask-Session     0.3.2
geographiclib     1.50
geojson           2.5.0
geopy             1.21.0
isort             5.7.0
itsdangerous      1.1.0
Jinja2            2.11.3
lazy-object-proxy 1.4.3
MarkupSafe        1.1.1
mccabe            0.6.1
pandas            1.2.1
pip               21.0.1
pylint            2.6.0
pymongo           3.11.3
regex             2020.11.13
setuptools        52.0.0.post20210125
taxon-parser      0.2.3
toml              0.10.2
tornado           6.1
Werkzeug          1.0.1
wheel             0.36.2
wrapt             1.12.1

In [26]:
import calendar

In [ ]:
x = "Herpestes ichneumon "

In [ ]:
y = x.split(" ")[0]

In [ ]:
y

In [ ]:
calendar.month_abbr[int(month)]

In [46]:
import pandas as pd
df = pd.read_csv("Species_def.csv", sep = ";")

In [47]:
df = df.head(100)

In [49]:
df

,long,lat,locality,province,year,month,kingdom,class,family,genus,species,common_name
0,-2.580,42.800,Aberasturi,Alava,2000,Jan,Animalia,Aves,Podicipedidae,Tachybaptus,Tachybaptus ruficollis,Zampullin comun
1,-2.580,42.800,Aberasturi,Alava,2001,Jan,Animalia,Aves,Podicipedidae,Podiceps,Podiceps cristatus,Somormujo lavanco
2,-2.580,42.800,Aberasturi,Alava,2001,Jan,Animalia,Aves,Podicipedidae,Tachybaptus,Tachybaptus ruficollis,Zampullin comun
3,-2.580,42.800,Aberasturi,Alava,2002,Jan,Animalia,Aves,Podicipedidae,Tachybaptus,Tachybaptus ruficollis,Zampullin comun
4,-2.580,42.800,Aberasturi,Alava,2003,Jan,Animalia,Aves,Podicipedidae,Podiceps,Podiceps cristatus,Somormujo lavanco
...,...,...,...,...,...,...,...,...,...,...,...,...
95,-0.410,38.812,Albufera de Gaianes,Alicante,2012,Jan,Animalia,Aves,Podicipedidae,Tachybaptus,Tachybaptus ruficollis,Zampullin comun
96,-0.410,38.812,Albufera de Gaianes,Alicante,2013,Jan,Animalia,Aves,Podicipedidae,Podiceps,Podiceps cristatus,Somormujo lavanco
97,-0.410,38.812,Albufera de Gaianes,Alicante,2013,Jan,Animalia,Aves,Podicipedidae,Tachybaptus,Tachybaptus ruficollis,Zampullin comun
98,-0.400,38.806,Albufera de Gaianes,Alicante,2019,Jan,Animalia,Aves,Podicipedidae,Tachybaptus,Tachybaptus ruficollis,Little Grebe
99,-2.634,42.861,Balsa de Zurbano,Alicante,2003,Jan,Animalia,Aves,Podicipedidae,Tachybaptus,Tachybaptus ruficollis,Zampullin comun

In [64]:
#get provinces
locator = Nominatim(user_agent="myGeocoder")
location = locator.reverse("42.861, -2.634")

In [65]:
loc = str(location)

In [87]:
geolocator = Nominatim(user_agent="geoapiExercises")
def city_state_country(lat, long):
    location = geolocator.reverse(coord, exactly_one=True)
    address = location.raw['address']
    province = address.get('province', '')
    return  province

In [ ]:
print(city_state_country("42.861, -2.634"))

In [67]:
loc.split(",")[3]

' Zurbano/Zurbao'

In [91]:
df["prov"] = df.apply(city_state_country([df["lat"], df["long"]]))

KeyError: 'lat'

In [37]:
def coord(locality):
     
    locator = Nominatim(user_agent="myGeocoder")
    location = locator.geocode(locality)
    loc = location.address
    x   = loc.split(",")[3].split("-")[0]
    return x

In [1]:
from geopy.geocoders import Nominatim

In [32]:
def coord(locality):
     
    locator = Nominatim(user_agent="myGeocoder")
    location = locator.geocode(locality)
    loc = location.address
    x   = loc.split(",")[3].split("-")[0]

    provinces = ["Cáceres"]

    if x in provinces:
        return x
        print(x)
        
    else:
        locator = Nominatim(user_agent="myGeocoder")
        location = locator.geocode(locality)
        loc2 = location.address
        loc2.split(",")[3]
        print(loc2)
    return loc2

In [33]:
coord("Parque Nacional Monfrague")

Parque Nacional de Monfragüe, Torrejón el Rubio, Monfragüe, Cáceres, Extremadura, 10694, España

'Parque Nacional de Monfragüe, Torrejón el Rubio, Monfragüe, Cáceres, Extremadura, 10694, España'

In [114]:
locator = Nominatim(user_agent="myGeocoder")
location = locator.geocode("Marcelo Celayeta  35, Pamplona")
lat, lon = (round((location.latitude), 3), (round(location.longitude, 3)))

In [115]:
lat, lon

(42.826, -1.655)

In [ ]:
print((location.latitude, location.longitude))

In [ ]:
get_genus(x)

In [3]:
from datetime import datetime
import re

In [ ]:
new = date.split("/")
new

In [ ]:
month = new[1]
month

In [ ]:
get_date(date)

In [ ]:
apple = 1
banana = 'f'
carrot = 3
fruitdict = {}

for i in ('apple', 'banana', 'carrot'):
    fruitdict[i] = locals()[i]
    
fruitdict

In [ ]:
dictionary = create_dict_insert()

In [4]:
def get_date (date):
    new = date.split("/")
    month = new[1]
    year = new[2].split(" ")[0]
    return month, year

In [5]:
def get_genus(sp):
    return sp.split(" ")[0]

In [6]:
def get_coord(city):
    try: 
        locator = Nominatim(user_agent="myGeocoder")
        location = locator.geocode(city)
        lat, lon = (round((location.latitude), 3), (round(location.longitude, 3)))
        return lat, lon
    except:
        lat = float('NaN')
        lon = float('NaN')
        return lat, lon

In [11]:
lat, lon = get_coord("barcelona")

In [12]:
lat, lon

(41.383, 2.177)

In [15]:
city2 = "jbsdfjkasbk"

In [16]:
date = "[05/Mar/2022 13:43:44]"

In [17]:
sp = "Herpestes ichneumon "

In [71]:
locality = ""

In [19]:
common_name = "Pato colorado"

In [20]:
scientific = "Lola lola"

In [21]:
def create_dict_insert (city, date, locality, common_name, species, kingdom = "Animmalia" ):
    lat, long = get_coord(city)
    month, year = get_date(date)
    genus = get_genus(species)
    dict_ = {}
    for i in ("kingdom", "lat", "long", "locality", "month", "year",   "genus", "common_name", "species"):
        dict_[i] = locals()[i]
    return dict_

In [23]:
dictionary = create_dict_insert(city2, date,  locality, common_name, scientific)

In [76]:
dictionary ={'kingdom': 'Animmalia',
 'lat': 45,
 'long': 456,
 'locality': 'barcelona',
 'month': 'Mar',
 'year': '',
 'genus': 'Lola',
 'common_name': 'Pato colorado',
 'species': 'Lola lola'}

In [77]:
def create_dict_insert (city, date, locality, common_name, species, kingdom = "Animmalia" ):
    lat, long = get_coord(city)
    month, year = get_date(date)
    genus = get_genus(species)
    dict_ = {}
    for i in ("kingdom", "lat", "long", "locality", "month", "year",   "genus", "common_name", "species"):
        dict_[i] = locals()[i]
        
        #check if the dictionary has any empty key. 
    any_empty_vals = bool(len(['' for x in dictionary.values() if not x]))
        
    if any_empty_vals:
        return True
    return dict_

In [78]:
dictionary = create_dict_insert(city2, date,  locality, common_name, scientific)

In [79]:
dictionary

True

In [91]:
check_form (dictionary)

True

In [80]:
def create_dict_insert (city, date, locality, common_name, species, kingdom = "Animmalia" ):
    lat, long = get_coord(city)
    month, year = get_date(date)
    genus = get_genus(species)
    dict_ = {}
    for i in ("kingdom", "lat", "long", "locality", "month", "year",   "genus", "common_name", "species"):
        dict_[i] = locals()[i]
    print(dict_)   
    #check if the dictionary has any empty key. 
    any_empty_vals = bool(len(['' for x in dict_.values() if not x]))
        
    if any_empty_vals:
        return "ohoh"
    return False

In [82]:
dictionary = create_dict_insert(city2, date,  locality, common_name, scientific)

{'kingdom': 'Animmalia', 'lat': nan, 'long': nan, 'locality': '', 'month': 'Mar', 'year': '2022', 'genus': 'Lola', 'common_name': 'Pato colorado', 'species': 'Lola lola'}

In [83]:
dictionary

'ohoh'

In [74]:
if not create_dict_insert(city2, date,  locality, common_name, scientific):
    print("ole")
else: 
    print("oh oh")

{'kingdom': 'Animmalia', 'lat': nan, 'long': nan, 'locality': '', 'month': 'Mar', 'year': '2022', 'genus': 'Lola', 'common_name': 'Pato colorado', 'species': 'Lola lola'}
oh oh

In [94]:
def insert_new(dictionary):
    if check_form(dictionary):
        return {"Sorry: Bad Request: there is already this quote"}
    insert(dictionary, f"{coll}")
    return {"Data_tets successfully inserted"}

In [95]:
insert_new(dictionary)

{'Sorry: Bad Request: there is already this quote'}

In [ ]:
import pandas as pd
sp = pd.read_csv("Species_data3.csv", sep = ";")

In [ ]:
sp.head(10)

In [ ]:
sp.shape

In [ ]:
locator = Nominatim(user_agent="myGeocoder")
location = locator.reverse((40.282, -5.010))

In [ ]:
print(location.raw)

In [ ]:
sp = sp.head(20)
sp.tail()

In [ ]:
import geopy
import pandas as pd


def get_zipcode(df, geolocator, lat_field, lon_field):
    location = geolocator.reverse((df[lat_field], df[lon_field]))
    return location.raw['address']['county']

geolocator = geopy.Nominatim(user_agent='myGeocoder')

sp["province"] = sp.apply(get_zipcode, axis=1, geolocator=geolocator, lat_field='lat', lon_field='long')

In [ ]:
sp.head(10)

In [ ]:
province = "hello"
common_name = "Lala"
month = "Jan"

In [ ]:
query = {'$and': [{'province':{'$regex': f"{province}"}}, {'common_name':{'$regex': f"{common_name}"}}, {'month':{'$regex': f"{month}", "$options" :'i'}}]}

In [59]:
obj = {"lat": -5.68, 
       "long": -8.694,
       "species": "Zaraìto", 
       "month": "Jun"}

In [60]:
query = {"$and": [{"lat":obj['lat']}, {"long":obj['long']}, {"species":obj['species']}, {"month":obj['month']}]}

In [61]:
query

{'$and': [{'lat': -5.68},
  {'long': -8.694},
  {'species': 'Zaraìto'},
  {'month': 'Jun'}]}

In [116]:
id =

In [118]:
d = dict(id=id)

In [119]:
d

{'id': '6481816548161561864'}

In [120]:
from bson import ObjectId

In [137]:
string = "6481816548161561864"

In [138]:
s = string.encode('utf-8')

In [139]:
s.hex()

'36343831383136353438313631353631383634'

In [140]:
if string is str:
    print(True)

In [142]:
def check(x):
    if string is str:
        return True

In [147]:
x = check(string)

In [148]:
if x:
    x = 2+2

In [150]:
print(x)

None

In [160]:
dictionary ={'kingdom': 'Animmalia',
 'lat': 45,
 'long': 456,
 'locality': 'barcelona',
 'month': 'Mar',
 'year': ' ' ,
 'genus': 'Lola',
 'common_name': 'Pato colorado',
 'species': 'Lola lola'}

In [161]:
for k, v in dictionary.items():
    if not any([k,v]):
        del d[k]

In [162]:
dictionary

{'kingdom': 'Animmalia',
 'lat': 45,
 'long': 456,
 'locality': 'barcelona',
 'month': 'Mar',
 'year': ' ',
 'genus': 'Lola',
 'common_name': 'Pato colorado',
 'species': 'Lola lola'}

In [164]:
d = {'': '', 'username': 'johndoe', 'email': 'johndoe@gmail.com'}

In [169]:
dict_2 = dict(x for x in d.items() if any(x))

In [170]:
dict_2

{'username': 'johndoe', 'email': 'johndoe@gmail.com'}

In [173]:
s =  "Hola hola"

In [174]:
len(s.split())

2

In [3]:
d ={'lat': 'nan',
 'long': 'nan'}

In [7]:
d = {'abc': 'abc', 'def': {'ghi': 'ghi', 'jkl': 'jkl'}}
for element in d.values():
    if isinstance(element, float):
        print("Nice!")
    else:
        print("oh oh")

oh oh
oh oh

In [2]:
import requests

In [3]:

from flask import Flask, request, jsonify
import requests
import pandas as pd

In [14]:
import calendar
import requests
import pandas as pd
from tqdm import tqdm
from time import sleep
from pygbif import species
from pygbif import occurrences as occ

In [15]:
response = requests.get('http://api.gbif.org/v1/occurrence/counts/datasets')
response.status_code

200

In [ ]:
data

In [20]:
import pymongo
from pymongo import MongoClient

In [21]:
client = MongoClient()

In [22]:
db = client.final

In [51]:
query = {"class": "Aves"}
project = {"lat": 1, "long": 1, "class": 1, "species": 1, "_id": 0}
res = db.species.find(query, project)

In [52]:
x = list(res)
x

[{'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.58,
  'lat': 42.8,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.87,
  'lat': 42.97,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.87,
  'lat': 42.97,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.87,
  'lat': 42.97,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.54,
  'lat': 42.83,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.55,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.55,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.55,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.55,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.55,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.55,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.55,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Platalea leucorodia'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63, 'lat': 42.86, 'class': 'Aves', 'species': 'Tadorna tadorna'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63, 'lat': 42.86, 'class': 'Aves', 'species': 'Ardea alba'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63, 'lat': 42.86, 'class': 'Aves', 'species': 'Ardea alba'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63,
  'lat': 42.86,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.63, 'lat': 42.86, 'class': 'Aves', 'species': 'Ardea alba'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.99,
  'lat': 42.78,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -1.714,
  'lat': 38.488,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.41,
  'lat': 38.812,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -0.41, 'lat': 38.812, 'class': 'Aves', 'species': 'Egretta alba'},
 {'long': -0.41,
  'lat': 38.812,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.41,
  'lat': 38.812,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -0.41,
  'lat': 38.812,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.41,
  'lat': 38.812,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -0.41,
  'lat': 38.812,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.4,
  'lat': 38.806,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.634,
  'lat': 42.861,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.545,
  'lat': 38.254,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.794,
  'lat': 36.706,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.729,
  'lat': 36.763,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.729, 'lat': 36.763, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -2.729,
  'lat': 36.763,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.759,
  'lat': 36.693,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.759,
  'lat': 36.693,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.759,
  'lat': 36.693,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.759,
  'lat': 36.693,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.759,
  'lat': 36.693,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.258,
  'lat': 36.797,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.258,
  'lat': 36.797,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.258,
  'lat': 36.797,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -1.774,
  'lat': 37.243,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -1.81,
  'lat': 37.201,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.639,
  'lat': 38.113,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -3.025,
  'lat': 36.888,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -3.025,
  'lat': 36.888,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -1.867,
  'lat': 37.268,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Platalea leucorodia'},
 {'long': 0.067,
  'lat': 38.645,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': 0.067,
  'lat': 38.645,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.675,
  'lat': 36.698,
  'class': 'Aves',
  'species': 'Platalea leucorodia'},
 {'long': -2.675,
  'lat': 36.698,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.675,
  'lat': 36.698,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.675,
  'lat': 36.698,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.816,
  'lat': 36.713,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.816,
  'lat': 36.713,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.816,
  'lat': 36.713,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Ixobrychus minutus'},
 {'long': -2.95, 'lat': 36.753, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Ixobrychus minutus'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95, 'lat': 36.753, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95, 'lat': 36.753, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95, 'lat': 36.753, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Nycticorax nycticorax'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Nycticorax nycticorax'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Ardeola ralloides'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.95, 'lat': 36.753, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Nycticorax nycticorax'},
 {'long': -2.95,
  'lat': 36.753,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.729,
  'lat': 36.763,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.729, 'lat': 36.763, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -2.729,
  'lat': 36.763,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.759,
  'lat': 36.693,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.759,
  'lat': 36.693,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Platalea leucorodia'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.221, 'lat': 36.769, 'class': 'Aves', 'species': 'Egretta alba'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Platalea leucorodia'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.221,
  'lat': 36.769,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.675,
  'lat': 36.698,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -2.675,
  'lat': 36.698,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -2.675,
  'lat': 36.698,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -2.233,
  'lat': 36.8,
  'class': 'Aves',
  'species': 'Bucanetes githagineus'},
 {'long': -0.545,
  'lat': 38.254,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -0.545,
  'lat': 38.254,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -0.545, 'lat': 38.254, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -0.545,
  'lat': 38.254,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.058, 'lat': 38.873, 'class': 'Aves', 'species': 'Netta rufina'},
 {'long': -0.058,
  'lat': 38.873,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -0.058, 'lat': 38.873, 'class': 'Aves', 'species': 'Egretta alba'},
 {'long': -0.058,
  'lat': 38.873,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.527,
  'lat': 38.29,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Podiceps nigricollis'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Tadorna tadorna'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Ixobrychus minutus'},
 {'long': -0.637,
  'lat': 38.172,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -5.1,
  'lat': 40.214,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -4.557,
  'lat': 40.878,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -4.589,
  'lat': 40.426,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -4.589,
  'lat': 40.426,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -4.589,
  'lat': 40.426,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -4.589,
  'lat': 40.426,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -4.589,
  'lat': 40.426,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -4.589,
  'lat': 40.426,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -4.689,
  'lat': 40.701,
  'class': 'Aves',
  'species': 'Mareca penelope'},
 {'long': -4.692,
  'lat': 40.694,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -4.692,
  'lat': 40.694,
  'class': 'Aves',
  'species': 'Podiceps cristatus'},
 {'long': -4.692,
  'lat': 40.694,
  'class': 'Aves',
  'species': 'Tachybaptus ruficollis'},
 {'long': -4.692,
  'lat': 40.694,
  'class': 'Aves',

In [53]:
df = pd.DataFrame(x, columns = ["long", "lat", "class", "species"])

In [55]:
df.head()

   long   lat class                 species
0 -2.58  42.8  Aves      Podiceps cristatus
1 -2.58  42.8  Aves  Tachybaptus ruficollis
2 -2.58  42.8  Aves  Tachybaptus ruficollis
3 -2.58  42.8  Aves      Podiceps cristatus
4 -2.58  42.8  Aves  Tachybaptus ruficollis

In [57]:
df = pd.read_csv("climate.csv")

In [63]:
df.head()

,Unnamed: 0,cold_temp,long,lat,warm_temp,elevation,Isothermality,Mean_Temp,Precipitation,Seasonal_temp
0,0,6.1,-7.9,43.8,21.3,226,42.9,13.0,38.8,320.8
1,1,6.7,-7.7,43.8,21.8,118,43.2,13.6,38.4,314.0
2,2,6.5,-8.0,43.7,21.6,159,43.8,13.4,39.4,315.3
3,3,6.5,-8.0,43.7,21.6,159,43.8,13.4,39.4,340.0
4,4,6.5,-8.0,43.7,21.6,159,43.8,13.4,38.1,315.3

In [60]:
df.shape

(4739386, 10)

In [61]:
df.drop_duplicates(subset= ["long", "lat"])

,Unnamed: 0,cold_temp,long,lat,warm_temp,elevation,Isothermality,Mean_Temp,Precipitation,Seasonal_temp
0,0,6.1,-7.9,43.8,21.3,226,42.9,13.0,38.8,320.8
1,1,6.7,-7.7,43.8,21.8,118,43.2,13.6,38.4,314.0
2,2,6.5,-8.0,43.7,21.6,159,43.8,13.4,39.4,315.3
130,130,6.3,-7.9,43.7,22.1,129,44.3,13.5,38.3,325.6
131,131,6.4,-7.8,43.7,22.3,127,44.6,13.6,37.8,330.0
132,132,6.1,-7.7,43.7,22.2,179,44.2,13.3,37.2,333.2
133,133,6.3,-7.6,43.7,22.3,155,44.4,13.5,37.4,330.2
134,134,6.2,-7.5,43.7,22.4,134,44.6,13.5,37.1,332.0
262,262,6.5,-7.4,43.7,22.7,65,45.0,13.9,37.7,331.8
263,263,7.0,-8.2,43.6,22.3,36,44.9,14.1,40.4,309.9
264,264,6.5,-8.1,43.6,22.0,130,44.2,13.6,39.7,319.5
265,265,6.1,-8.0,43.6,22.0,181,44.1,13.3,39.2,330.2
393,393,5.8,-7.9,43.6,22.4,178,44.6,13.3,38.2,339.8
394,394,5.1,-7.8,43.6,22.2,328,44.2,12.6,38.0,354.9
395,395,4.7,-7.7,43.6,22.1,363,44.3,12.4,37.6,359.5
396,396,5.6,-7.6,43.6,22.6,204,45.0,13.2,37.4,348.5
397,397,4.8,-7.5,43.6,22.3,362,44.5,12.5,36.7,362.2
525,525,5.6,-7.4,43.6,22.7,203,45.2,13.2,36.5,349.6
526,526,6.2,-7.3,43.6,23.2,74,45.6,13.9,37.8,341.4
527,527,5.7,-6.2,43.6,21.9,62,43.2,13.4,32.2,341.6
528,528,5.6,-6.0,43.6,22.4,11,42.5,13.8,29.6,358.1
529,529,5.2,-5.9,43.6,22.4,55,41.9,13.5,29.1,367.7
530,530,5.2,-5.8,43.6,22.5,49,41.5,13.6,28.9,373.2
531,531,6.7,-8.3,43.5,22.2,98,44.3,13.8,41.0,315.0
659,659,6.5,-8.2,43.5,22.8,77,45.2,13.9,40.5,326.2
787,787,6.1,-8.1,43.5,22.7,134,45.2,13.6,40.1,336.3
915,915,5.6,-8.0,43.5,22.6,186,45.0,13.3,39.5,343.7
17299,17299,4.5,-7.9,43.5,22.2,409,44.2,12.3,39.5,367.5
17427,17427,3.9,-7.8,43.5,22.0,510,43.8,11.8,39.0,379.3
17555,17555,3.9,-7.7,43.5,22.2,489,43.9,11.9,38.6,379.0
...,...,...,...,...,...,...,...,...,...,...
4721576,4721576,14.2,-16.7,28.0,28.1,118,53.9,20.7,84.5,241.6
4721577,4721577,13.7,-16.6,28.0,28.8,157,54.2,20.6,82.5,253.9
4721578,4721578,14.0,-16.5,28.0,29.2,97,54.8,20.9,85.1,251.9
4721706,4721706,12.2,-15.8,28.0,27.5,301,50.5,19.1,78.7,273.4
4721834,4721834,9.4,-15.7,28.0,26.4,738,45.8,16.6,74.4,325.4
4721962,4721962,7.1,-15.6,28.0,25.7,1092,44.1,14.6,73.3,362.4
4722090,4722090,8.8,-15.5,28.0,26.1,777,45.7,16.0,72.3,327.3
4738474,4738474,13.9,-15.4,28.0,28.3,58,52.7,20.5,75.1,253.9
4738602,4738602,14.6,-14.5,28.0,25.3,5,47.8,19.8,82.0,210.3
4738730,4738730,13.1,-14.4,28.0,27.0,182,51.7,19.7,83.4,241.4
4738731,4738731,13.4,-14.3,28.0,27.6,101,52.4,20.1,85.5,244.8
4738732,4738732,14.7,-18.0,27.9,26.4,153,48.7,19.9,85.3,224.7
4738733,4738733,14.7,-17.9,27.9,26.6,160,49.0,20.0,87.5,225.7
4738734,4738734,12.4,-15.8,27.9,28.2,328,49.6,19.5,78.2,282.8
4738735,4738735,10.9,-15.7,27.9,28.4,540,48.8,18.4,75.4,317.1
4738736,4738736,9.6,-15.6,27.9,28.0,743,47.4,17.4,74.6,340.9
4738737,4738737,10.0,-15.5,27.9,28.2,666,47.3,17.8,73.4,338.0
4738865,4738865,14.1,-15.4,27.9,28.4,45,52.8,20.8,79.7,252.0
4738866,4738866,14.3,-18.1,27.8,26.3,192,49.9,19.8,85.3,230.7
4738867,4738867,14.3,-18.0,27.8,26.8,139,49.5,19.9,85.3,237.8
4738995,4738995,14.2,-17.9,27.8,26.4,262,48.2,19.6,84.7,235.3
4738996,4738996,13.9,-15.8,27.8,28.3,110,51.5,20.6,82.2,252.5
4738997,4738997,13.4,-15.7,27.8,28.5,193,51.4,20.3,80.7,264.5
4738998,4738998,13.2,-15.6,27.8,28.9,217,51.7,20.3,78.5,274.1
4738999,4738999,12.8,-15.5,27.8,28.9,268,50.8,20.0,76.9,282.8
4739127,4739127,12.6,-18.1,27.7,26.0,525,48.9,18.5,81.3,254.9
4739128,4739128,11.2,-18.0,27.7,25.8,775,47.9,17.4,79.7,278.6
4739256,4739256,14.4,-15.6,27.7,28.4,13,52.7,21.0,81.6,243.3
4739257,4739257,14.2,-15.5,27.7,28.7,8,53.5,21.0,81.7,246.6
4739258,4739258,14.7,-18.0,27.6,28.4,121,54.9,20.9,87.2,235.1

In [ ]:
def lafuncionmolona(x):
    locator = Nominatim(user_agent="myGeocoder", timeout=10)
    location = locator.reverse(x)
    data = location.raw
    try:
        return data.get("address").get("state")
    
    except: 
        return "unknown"